### ISSUE TITLE
Cannot build dev_dns_updater.go

### ISSUE THREAD

**Issue by inductor** [pixie-io/pixie#406] opened 2022-02-21 07:37 UTC
**Describe the bug**

```
$  go build src/utils/dev_dns_updater/dev_dns_updater.go
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg
/usr/local/go/src/runtime/internal/sys/stubs.go:16:7: StackGuardMultiplier redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch.go:27:74: previous declaration
```

Here's my Go version

```
$ go version
go version go1.17.7 linux/amd64
```

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version
- K8s cluster version
- Node Kernel version
- Browser version

**Additional context**

**Comment by yzhao1012** [comment] 2022-02-25 18:54
I couldn't reproduce this on my host. Is there other details missing from the report?

**Comment by htroisi** [comment] 2022-02-25 19:04
Could this be an issue with a [corrupt go installation](https://github.com/golang/go/issues/48134)?

**Comment by aimichelle** [comment] 2022-03-11 18:08
Closing as we can not reproduce, and would require more information about the build environment.

**Closed by aimichelle** 2022-03-11 18:08 UTC
