### ISSUE TITLE
vizier-metadata-0 pod is not starting properly

### ISSUE THREAD

**Issue by fsklenar** [pixie-io/pixie#1484] opened 2023-06-14 12:19 UTC
**Describe the bug**
We have 3 EKS clusters in AWS, selfhosted Pixie-Cloud installation.
There is no problem on 2 EKS Clusters with Pixie, but on one cluster vizier-metadata-0 pod is not starting properly - it stuck on level=info msg="Gained leadership" and next step -  "Loading HTTP TLS certs" is missing as we can see this message on pods on other clusters with functional Pixie. 
Please do you have an idea what is missing or what should I try. Thank you!

**To Reproduce**
Pixie installation

**Expected behavior**
vizier-metadata-0 is running OK with correct healthcheck

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```
[pixie_logs_20230614131606.zip](https://github.com/pixie-io/pixie/files/11745128/pixie_logs_20230614131606.zip)

**App information (please complete the following information):**
- Pixie version: Built 2023.05.02.08.07
- K8s cluster version: v1.23.16-eks-48e63af
- Node Kernel version: 5.4.231-137.341.amzn2.x86_64
- Browser version: N/A

**Comment by aimichelle** [comment] 2023-06-15 16:36
Hello @fsklenar ! Thanks for sending along that debug information. A couple questions:
- Do you know what differences there are between this EKS cluster vs the two it is working on? What are the relative sizes of these clusters (for example, # of nodes, # of pods per node).
- I would like to add some more logs for debugging this issue since it's not immediately clear which part in the metadata's startup sequence is getting stuck. Would you be able to bump the image tag once those log changes are released (around Tuesday next week), then reshare the logs for the metadata pod?

Thanks!

**Comment by fsklenar** [comment] 2023-06-16 07:35
Hello @aimichelle, thank you very much for your reply.

We are not aware of differences between EKS clusters (same K8S version, same Node types and images), maybe difference is in number of Nodes:
- EKS clusters with functional Pixie have around 9-12 nodes (around 35 pods per Node)
- "Problematic" EKS cluster is larger with around 45 nodes (around 35 pods per Node)  
So as far as I understand it, around Tuesday next week you will deploy new image (with new tag) and we can use this image with enhanced logging -  yes of course it would be great. 
Please let me know once new image is ready.

Thank you.

**Comment by imdevin567** [comment] 2023-06-24 15:49
I have a seven node cluster created with kubeadm and have this issue. I can confirm @fsklenar's workaround above works.

**Comment by aimichelle** [comment] 2023-07-12 17:50
@fsklenar, thanks a bunch for all of that information! Using what you found, I believe I was able to pinpoint the issue and just merged in a fix for it: https://github.com/pixie-io/pixie/pull/1611
It should be pulled into next week's release. Once that release is out, I'll reach back out to this thread. Would you all be willing to give it a try to confirm that it fixes your issue?

Thank you everyone!

**Comment by fsklenar** [comment] 2023-07-13 08:56
@aimichelle thank you very much for feedback, of course I am looking forward for the new image I can test and will provide feedback to you.

**Comment by vihangm** [comment] 2023-08-01 16:40
This was fixed and released as https://github.com/pixie-io/pixie/releases/tag/release%2Fvizier%2Fv0.14.3

**Closed by vihangm** 2023-08-01 16:40 UTC
Labels: kind/bug, area/deployment, priority/important-soon, triage/accepted, area/vizier, go

**Comment by fsklenar** [comment] 2023-08-02 07:01
Hi @vihangm @aimichelle I can confirm this image 14.3 fixed the issue.
Thank you all!
