### ISSUE TITLE
[Deploy] support image override in `px deploy`、px-operator and charts

### ISSUE THREAD

**Issue by mars1024** [pixie-io/pixie#538] opened 2022-07-20 06:37 UTC
**Is your feature request related to a problem? Please describe.**

Now, pixie is providing different ways to deploy pixie cloud and vizier, all is going well expect the image download.
Unfortunately, `px deploy` and charts do not provider an image override option, also the statefulset、daemonset and deployment provisioned by px-operator can not be configured either.
In our self-hosted k8s cluster, gcr is unreachable, so..., I have to download and push images to our image registry, then edit the k8s objects(sts, deploy, ds) by myself one by one.
It is a hard and unstable way.

**Describe the solution you'd like**
I'd like to see container image can be override by `px deploy`、px-operator and charts.

**Additional context**

**Comment by aimichelle** [comment] 2022-07-20 19:06
Hi @mars1024 ! Thanks for filing this--this is something we're starting to hear frequently. I'm going to close this as a duplicate of https://github.com/pixie-io/pixie/issues/473 so that there's just one thread we can send out our updates.

**Closed by aimichelle** 2022-07-20 19:06 UTC

**Comment by shane-emery** [comment] 2022-07-28 22:30
Hello,
My organization is in the same boat and we need the ability to specify a custom internal docker repo.  We have no issue with retagging the images to our internal, but need the flag some way some how.
