### ISSUE TITLE
Only partial data is being captured by the pixie agent - No interpod traffic

### ISSUE THREAD

**Issue by benmathews** [pixie-io/pixie#1056] opened 2023-03-15 14:28 UTC
**Describe the bug**
Only partial data is being captured by the pixie agent

**To Reproduce**
1. Install pixie with `px deploy`
2. Run the `px/cluster` script at https://work.withpixie.ai/live
3. Observe that pixie knows about namespaces and pods, but none of the traffic between them.
![image](https://user-images.githubusercontent.com/446380/225333831-62503acb-d68b-4f29-8368-f431d61f14df.png)
4 Run the `px/cluster` script from the CLI
```
➜ px run px/cluster
<snip>
Table ID: Services
  SERVICE                                                                                                                                                                                            POD COUNT  HTTP LATENCY IN  HTTP REQ THROUGHPUT IN  HTTP ERROR RATE IN  INBOUND CONNS  OUTBOUND CONNS  
  ["nebo/history-headless","nebo/history"]                                                                                                                                                           7                           0.000000 /sec           0.00 %              0 B/sec        0 B/sec         
  nebo/propm-properties-api                                                                                                                                                                          3                           0.000000 /sec           0.00 %              0 B/sec        0 B/sec         
<snip>
```

**Expected behavior**
Pixie should know about the HTTP, kafka, etc. traffic.

**Logs**
[pixie_logs_20230315080754.zip](https://github.com/pixie-io/pixie/files/10980870/pixie_logs_20230315080754.zip)

**App information (please complete the following information):**
```
➜ px version
Pixie CLI
0.7.17+Distribution.1f8cdfb.20220815151559.3.jenkins
☸ sekube (pl) in ~ via 🐹 v1.20.1 
➜ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2023-01-04T19:18:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
$ uname -a
Linux se-kube-36.vivintsky.com 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

**Comment by benmathews** [comment] 2023-03-20 16:17
> Hey @benmathews, can you provide more information on what services you are running, what network protocols those services are using and if the traffic is encrypted. In order to properly debug this, we need a way to reproduce the partial data collection you are experiencing.

We have kafka, rabbitmq, redis, Memcached, MongoDB, HTTP, gRPC and probably others running. We use DNS, TCP, and UDP. gRPC traffic is encrypted by default. Everything else is unencrypted.

**Comment by ddelnano** [comment] 2023-03-21 16:21
Even if installing the linux-headers fixes the issue, there are some possible improvements here.

The logs provided indicate that the first source connector fails with the following error:

```
Failed to install packaged Linux headers to /lib/modules/5.15.0-58-generic, error: Not Found : No kernel config found. Searched: /proc/config,/proc/config.gz,/host/boot/config-5.15.0-58-generic,/host/lib/modules/5.15.0-58-generic/config,/proc/1/root/media/sr0/boot/config-virt,/proc/1/root/media/vda/boot/config-virt.
```

Subsequent source connector creations fail with a different error:

```
Failed to install packaged Linux headers to /lib/modules/5.15.0-58-generic, error: Internal : Refusing to clobber existing directory: /usr/src/linux-headers-5.15.90-pl.
```

After we install the prepackaged headers, there are [patches](https://github.com/pixie-io/pixie/blob/f318c93257ecd6afc397449291e9ec2b7be83475/src/stirling/utils/linux_headers.cc#L406) that are applied to the header files. My suspicion is that the prepackaged linux-headers installation process doesn't clean up after itself if it fails within the patching process. This results in the second and later source connector creations to fail with a different error because there is already a headers directory present.

Assuming that's the case, there is additional hardening we could add to the prepackaged header installation (ensuring it always fails with the first error by making sure it cleans up properly).

However, what is described above is just another symptom to the real problem. If your instance's kernel config was located, the initial failure wouldn't have occured.

@benmathews what type of kernel are you using? From the logs provided, I thought it was an upstream Ubuntu kernel (stock Ubuntu focal install). If that was the case, I wouldn't expect our process for finding a host's [kernel config](https://github.com/pixie-io/pixie/blob/f318c93257ecd6afc397449291e9ec2b7be83475/src/stirling/utils/linux_headers.cc#L303) to fail (the first error).

Is there any customization you've done that would have removed the kernel config from disk? Our code currently searches [these filepaths](https://github.com/pixie-io/pixie/blob/f318c93257ecd6afc397449291e9ec2b7be83475/src/stirling/utils/linux_headers.cc#L307) to find the kernel config.

**Comment by benmathews** [comment] 2023-03-21 21:36
My coworker says "We currently delete the config file to save space. The kernel we use is linux-generic-hwe-20.04"

**Comment by benmathews** [comment] 2023-03-21 22:12
I would agree that the config cleanup seems a false economy. 

The node I was testing on gets around 2GB/s of inbound network (container_network_receive_bytes_total). Other nodes range from 1.5GB to 3.5GB of inbound network traffic. 

I addressed the mix of services [above](https://github.com/pixie-io/pixie/issues/1056#issuecomment-1476539595).

**Comment by ddelnano** [comment] 2023-03-21 22:39
> I addressed the mix of services above

Apologies for misremembering that detail!

I would recommend increasing the [PL_TABLE_STORE_DATA_LIMIT_MB](https://github.com/pixie-io/pixie/blob/e9b91ee6c9f61d7e4b90d2d3532c320ff8c53a88/src/vizier/services/agent/pem/pem_manager.cc#L26) value and possibly consider changing [PL_TABLE_STORE_HTTP_EVENTS_PERCENT](https://github.com/pixie-io/pixie/blob/e9b91ee6c9f61d7e4b90d2d3532c320ff8c53a88/src/vizier/services/agent/pem/pem_manager.cc#L33). There is a previous [slack conversation](https://pixie-community.slack.com/archives/CQ63KEVFY/p1645496919833239?thread_ts=1645472267.359259&cid=CQ63KEVFY) that describes these settings in more detail and how it can be changed with [helm](https://pixie-community.slack.com/archives/CQ63KEVFY/p1645573682185899?thread_ts=1645472267.359259&cid=CQ63KEVFY).

If tweaking the values specified above doesn't stabilize the cluster, I think it would be best for us to continue the discussion in the Pixie slack (which it seems you have joined). The original issue was caused by the missing linux headers and kernel config, and surfaced a possible improvement we can make for hardening the packaged header installation (as described [here](https://github.com/pixie-io/pixie/issues/1056#issuecomment-1478161896)).

The inability to ingest the data into Pixie's underlying tables seems separate. Once we understand this second issue better, we can take the appropriate next steps (open up another issue, etc).

**Comment by benmathews** [comment] 2023-03-23 20:50
I increased PL_TABLE_STORE_DATA_LIMIT_MB to 2.5GB and am able to write data out. I'll roll all the pem pod on each nodes in the morning but anticipate no problems with that. 

@ddelnano thank you for working through this with me.

**Comment by ddelnano** [comment] 2023-03-24 20:53
@benmathews glad to hear that stabilized your pixie deployment!

I've created #1092 to follow up with the linux header install hardening I mentioned. In addition to that, I think there is an opportunity to make the out of the box Pixie experience more stable for high throughput nodes like yours (default table store size might need to scale as pod memory is increased, determining a way to address the initial OOMs you experienced).

Since this is resolved, I'll close this and any further follow up can happen in additional GitHub issues.

**Closed by ddelnano** 2023-03-24 20:53 UTC
