### ISSUE TITLE
arm64 containers

### ISSUE THREAD

**Issue by ruckc** [pixie-io/pixie#250] opened 2021-05-06 00:16 UTC
**Is your feature request related to a problem? Please describe.**
Please support arm64 container architectures.  We are unable to deploy pixie on our arm64 kubernetes cluster.

**Describe the solution you'd like**
Support multiple architecture containers, primarily amd64/arm64

**Comment by HaveFun83** [comment] 2021-06-20 09:10
:+1:  Will be great to see multi-arch support here

**Comment by tmancill** [comment] 2022-05-10 00:42
Also see #147.

**Comment by aimichelle** [comment] 2022-09-21 16:47
Closing as a duplicate of https://github.com/pixie-io/pixie/issues/147. Please look at that issue to track any updates!

**Closed by aimichelle** 2022-09-21 16:47 UTC
Labels: triage/duplicate, needs-triage
