### ISSUE TITLE
Deploy Pixie Control Plane via Helm(V3)

### ISSUE THREAD

**Issue by anshrma** [pixie-io/pixie#452] opened 2022-06-02 17:42 UTC
**Is your feature request related to a problem? Please describe.**
Currently deploying self managed Pixie is a series of Kustomize commands and additional manual steps around DNS setup, cert management, which makes it difficult to install , manage and automate.

**Describe the solution you'd like**
If there is a helm chart available for installing Pixie control plane we can use (1) External DNS Provider operator for any  cloud implementation of DNS, making DNS setup easier using annotations. (2) Exposing Pixie K8 services via load balancers , again using annotations. (3) Use cloud specific frameworks/blueprints, example [EKS Blueprints for Terraform](https://github.com/aws-ia/terraform-aws-eks-blueprints) to create base K8 infrastructure which conforms to best practices without management overheads and stitch Pixie Control Plane deployment in it.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aimichelle** [comment] 2022-07-12 23:58
Closing this as a duplicate of https://github.com/pixie-io/pixie/issues/452.

**Closed by aimichelle** 2022-07-12 23:58 UTC
Labels: kind/feature, priority/important-soon, triage/accepted, area/cli
