### ISSUE TITLE
JAVA flamegraph not showing the complete stack.

### ISSUE THREAD

**Issue by c3-pranjaysagar** [pixie-io/pixie#595] opened 2022-09-15 23:51 UTC
Steps followed 
- Complete tutorial for deploying the self hosted pixie
- Find an issue where stack in the flamegraph shows the hexa-decimal values
- based on the discussion  on the issue https://github.com/pixie-io/pixie/issues/592#issue-1372204593 manually edited the pem daemonsets.
- Hexadecimal values finally resolved to method calls

Current Issue
- the y-depth stack trace is incomplete as many of the method calls are missing in the stack. At what point does the flamegraph cutoff the stack at the top?
- Also on many stacks the value is interpreter[xx]

System information

java version - `openjdk version "17.0.2"
Environment - currently Azure

**Comment by etep** [comment] 2022-09-16 18:04
Hi @c3-pranjaysagar ,

The best case scenario for debugging this is if you could supply a mostly self-contained way to reproduce the bug. If you have an application that you can create an image and a yaml for, we can create a cluster on Azure (or elsewhere) and deploy it and see the bug reproduce.

Is it possible to follow this route?

**Comment by oazizi000** [comment] 2022-11-01 19:59
@c3-pranjaysagar We're not able to reproduce this right now, so closing. But feel free to re-open with more details, and we'll take a look!

**Closed by oazizi000** 2022-11-01 19:59 UTC
Labels: kind/bug, triage/needs-information, area/datacollector
